### PR TITLE
Updated some webdriver versions and URLs in the Download page

### PR DESCRIPTION
**Pull request by einsteinsfool**

### CODE REVIEW

**Comment by shs96c** [comment]
My sincere apologies for not looking at this sooner. The PR appears to need a rebase, but a quick look suggests that the new style for the pages leaves the specific versions out (partly because, I suspect, we've not been great at keeping things up to date) Would it be possible to rebase this change?

**Comment by einsteinsfool** [comment]
No problem.
Which changes of mine would you like to keep? The current live version is more general now - no version numbers, no release dates, no changelog link to the current version. Would you like me to fix that and add all of these things back? I don't mind closing this PR if you won't plan to maintain the download page and thus prefer the general view.

**Comment by shs96c** [comment]
Given that we've not been great at keeping this page up to date, perhaps it's best to leave the specific details out. If you think we can keep updating the files as we do releases (and, really, we should) then please update the details. I'm happy either way, so please do what you think is best.

**Comment by einsteinsfool** [comment]
No problem. I maked this PR when there were specific versions present, so I guess in this case it should be leaved as it is. Thanks for the reply.

**Pull request closed without merging**
