### PR TITLE
Adds JS framework information

### PR DESCRIPTION
**Pull request by klamping**

### CODE REVIEW

**Comment by ddavison** [comment]
I believe this specific section is talking about "testing" frameworks, not necessarily selenium frameworks.

**Comment by klamping** [comment]
Yeah, I was thinking that might be that case after running across this page: http://www.seleniumhq.org/download/#thirdPartyLanguageBindings

From the list, I'd say [NightwatchJS](http://nightwatchjs.org/) still fits. What do you think?

**Comment by lukeis** [comment]
yeah, it's specific framework to deal with selenium, but it is a 'test runner' too.... and since every one in javascript land wants to write their own...  ¯\_(ツ)_/¯

**Comment by klamping** [comment]
Thanks!

**Pull request merged**
