### PR TITLE
Adds Usetrace.com testing service to the ecosystem list.

### PR DESCRIPTION
**Pull request by avuori**

### CODE REVIEW

**Comment by lukeis** [comment]
Your site doesn't mention selenium anywhere in your site except nested inside [one pdf](https://www.google.com/?q=site:usetrace.com+selenium)

I'm not inclined to accept this patch to the ecosystem. We'd be more than happy to have you added to the [Selenium Sponsors](http://www.seleniumhq.org/sponsors/). See the [sponsor page](http://www.seleniumhq.org/sponsor/) for more information.

**Comment by avuori** [comment]
Hi lukeis,

what are the requirements to be added to the ecosystem list? We've built on top of Selenium providing a different user interface from what the language bindings or selenium ide offer.

**Comment by lukeis** [comment]
The "ecosystem" is meant for things that somehow show a strong usage of selenium or contributes to the project in some way. It is not meant to advertise anyone's product that may be using selenium under the hood. 

If your product doesn't show clear ties to the selenium project it will not be listed on the page. If others currently do not either, they likely updated their sites after initially having relevant content and will need to be removed from the ecosystem page as they no longer meet the criteria. 

The sponsors page, which I linked previously, is more suited for a site like yours (yes, I understand that is essentially asking for money, but we also don't like to provide free links to any company that wants one)

**Comment by avuori** [comment]
lukeis,

thanks for the details. Asking money is fine, you're doing a very important project and we're thankful for that. We'll consider the sponsorship.

**Pull request closed without merging**
