### PR TITLE
Add link to Perl 6 bindings

### PR DESCRIPTION
**Pull request by azawawi**
This is a currently working implementation that works with ```PhantomJS``` via ```ghostdriver```.

### CODE REVIEW

**Comment by lukeis** [comment]
Any particular reason you chose to make a new fork rather than contribute to the existing perl bindings? Fragmentation here is not a good thing for users. 

Also it appears your bindings *only* work with phantomjs? (Or is it the only concrete driver and the rest use remote?)

**Comment by ddavison** [comment]
looks like his bindings are in the official perl 6 modules directory: http://modules.perl6.org/

**Comment by azawawi** [comment]
It is for Perl 6 which is coming to you this christmas :+1:

**Comment by lukeis** [comment]
so you're saying Perl and 'Perl 6' are not related at all? There's no way a Perl 6 project could live side by side with a Perl project? It would make sense to point users to the same place and believe me, on an open source project you want as many people collaborating as possible (and it looks like the other perl project is fairly active)

**Comment by azawawi** [comment]
@lukeis Thanks for your valuable feedback. Yes, Perl 6 is the next generation Perl. Please take a look at http://perl6.org. 

There is also [Inline::Perl5](https://github.com/niner/Inline-Perl5) for using Perl 5 modules within Perl 6 but one needs to follow some [build instructions](https://github.com/niner/Inline-Perl5#building) for it to work properly.

Also I already wrote a [Parse::Selenese](https://github.com/azawawi/perl6-parse-selenese) module using [Perl 6 Grammars](http://doc.perl6.org/language/grammars) in an effort to automatically convert test suites and test cases into Perl 6 code from the Selenium IDE.

**Comment by ddavison** [comment]
I don't see a problem with this.. I've seen major languages deviate entirely (hence "major" version [very little, or no backwards compatibility)

Perl5:

```perl
my $driver = Selenium::Remote::Driver->new;
$driver->get('http://www.google.com');
print $driver->get_title . "\n"; # "Google"
```

Perl6:

```perl
my $driver = Selenium::WebDriver::PhantomJS;
$driver.url("http://google.com");
say "Title: "         ~ $driver.title;
```

The dialect is completely different.

**Comment by azawawi** [comment]
@ddavison Thanks. I fixed the Perl 6 example to include the missing ```.new``` call. My bad :+1: 

Also now firefox (via the webdriver extension) and chrome (via the chromedriver) are now working.

**Comment by lukeis** [comment]
while I appreciate the nuances of a major version update. My point is more so that any effort should be in conjunction with the other already existing project, rather than spinning off a new project.

That being said, I'll merge this... begrudgingly :)

**Comment by azawawi** [comment]
Thanks :+1:

**Comment by cygx** [comment]
@lukeis Perl6 is not the next iteration of Perl5, but a 'sister language' in the same family. Think of Perl5 vs Perl6 as C vs C++ or even C++ vs D.

**Comment by andreastt** [comment]
Unlike Python 3, Perl 6 is actually an entirely new language for all practical purposes.

**Pull request merged**
