### PR TITLE
expanded seConf to selenium conf and removed loading gif

### PR DESCRIPTION
**Pull request by manoj9788**
After my previous commit to this page, due to some reasons I get to see the loading.gif being shown all the time. Just removed it now and looks good on my local. Should be on the prod site as well.

### CODE REVIEW

**Comment by ddavison** [comment]
that loading actually does something.  I didn't really agree with the initial merge without a further change.

that loading gif actually will disappear after JavaScript gets done reading the nearest events from a google calendar.

**Comment by ddavison** [comment]
the code in question is [here](https://github.com/SeleniumHQ/www.seleniumhq.org/blob/master/src/main/webapp/js/events.js#L12-L32).

**Comment by ddavison** [comment]
I also believe that your merge that was put in is the source of the breakage of that spinner :)

**Comment by manoj9788** [comment]
@ddavison  I realized that due to my previous commit it might have been the cause for that spinner. I have said the same in my comment. I didn't change anything  to an existing code, but just added a table. https://github.com/SeleniumHQ/www.seleniumhq.org/commit/532f0a1de92d6a7febf5fcd9439ca373483f83d1

For many years the Events page has been empty at least since 2010 (I guess).  If it refers to a Google calendar and that's is the right way to do it, then who shall give more info about it ? 
[OR] I being from planning committee, take the responsibility to maintain this page with updates. - Manually like above.
Let me know what shall be done. Happy to be corrected.

**Comment by lukeis** [comment]
it hasn't been empty since 2010... Santi only added it in 2012 ;)

The calendar was managed previously by Ashley... and I guess no one else really added anything to it? (or the calendar got cleared?).

But we should probably use that calendar and drop in the Selenium conferences rather than have this table at all.

**Comment by manoj9788** [comment]
Here comes Luke :)  2012? OK, still empty for 3 years lol :)
I think it hasn't been added at all. May be if @santiycr  provides some info about it, I can take it up and work on it.

**Comment by lukeis** [comment]
Well, the display limits the time range that is shown, so it wasn't empty for 3 years.... But the google calendar does need some attention. I'll look up tomorrow either how to get permission on the calendar or create a new one since this one seems abandoned.

**Comment by manoj9788** [comment]
OK Luke

**Comment by lukeis** [comment]
i went with a slightly different approach and updated the page...

**Comment by manoj9788** [comment]
Looks good @lukeis :)
Please add me to the calendar as well. Should I raise a Github issue ?

**Pull request closed without merging**
