### PR TITLE
Add-on for reading a csv fle

### PR DESCRIPTION
**Pull request by abhijain2618**
I want to add link to my blog so that people can use this add-on.

### CODE REVIEW

**Comment by andreastt** [comment]
@lukeis, what's our policy on this?  From the list it looks like we basically accept everything?

**Comment by lukeis** [comment]
usually, except here it seems that the IDE plugins are under h3 sections and this PR seems to be out of place.

@abhijain2618 can you move your addition to just above the SeLite section header:
https://github.com/abhijain2618/www.seleniumhq.org/blob/patch-1/src/main/webapp/download/index.jsp#L601

**Comment by abhijain2618** [comment]
Thank you Lukeis and Andreastt for your comment, i have updated changes as suggested by you.

**Comment by abhijain2618** [comment]
@lukeis  can you help me move my changes? I am new here.

Thank You

**Comment by ddavison** [comment]
merging as you did what @lukeis asked :+1:

**Pull request merged**
