### PR TITLE
New Selenium IDE project page and docs

### PR DESCRIPTION
**Pull request by corevo**
In order to keep the old IDE's docs, I moved them to chapter 6 (so I had to move everything after it one chapter up).  
I chose 6 because it comes right after Selenium 1 chapter.  
Anyway I changed chapter 2 to be up to date with the new IDE.

### CODE REVIEW

**Comment by lukeis** [comment]
renaming all those chapters changes the links.... changes everyone's bookmarks or references. I'd like to not see that happen. I would suggest moving the 'old' IDE docs to the last chapter for now, so other chapters are not affected.

**Comment by corevo** [comment]
It's a problem that the urls are based on chapter numbers rather than names 😬
I'll change it

Cheers,
Tom

**Comment by corevo** [comment]
The best solution would've been to 301 the moved pages.  
Oh well 🐢

**Comment by lukeis** [comment]
better solution? move everything to new documentation ( https://github.com/SeleniumHQ/docs ) and change the sehq site to redirect to their. ;)

**Comment by lukeis** [comment]
looks ok to me 👍 feel to merge

**Pull request merged**
